kind: Service
apiVersion: v1
metadata:
  name: cheapest-exchange
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: cheapest-exchange