apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications-production
resources:
- ../../base
- namespace.yaml
transformers:
- labels.yaml
# patchesStrategicMerge:
# - |
#   apiVersion: apps/v1
#   kind: Deployment
#   metadata:
#     name: cheapest-exchange-api
#   spec:
#     template:
#       spec:
#         containers:
#           - name: cheapest-exchange-api
#             resources:
#               requests:
#                 cpu: 150m
#                 memory: 150Mi
replicas:
- count: 3
  name: cheapest-exchange-api
