name: Publish Docker Image

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'deploy/**'
  release:
    types:
      - published

jobs:

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run build --if-present
        
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        id: bump_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
          RELEASE_BRANCHES: develop

      - name: Extract number from new tag
        id: version_number_extract
        env:
          NEW_TAG: ${{ steps.bump_tag.outputs.new_tag }}
        run: |
          echo ::set-output name=version::$( echo $NEW_TAG | sed 's/^.//')

      - name: Print latest version number string
        env:
          NEW_TAG: ${{ steps.bump_tag.outputs.new_tag }}
        run: |
          echo ${{ steps.bump_tag.outputs.new_tag }}
          echo ${{ steps.bump_tag.outputs.tag }}
          echo ${{ steps.bump_tag.outputs.part }}
          echo ${{ steps.version_number_extract.outputs.version }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

      -
        name: Image tags
        run: echo "${{ steps.docker_meta.outputs.tags }}"

  update-dev-image:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'heads')
    needs:
    - build
    steps:
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: 3.8.6
    - run: git clone https://${GITHUB_TOKEN}@github.com/bikashpoudel2011/fleet-infra.git .
      env:
        REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: kustomize edit set image bikashpoudel2011/cheapest-exchange-rt:sha-$(git rev-parse --short $GITHUB_SHA)
      working-directory: ./deploy/overlays/staging
    - run: git add .
    - run: |
        git config user.email "$EMAIL"
        git config user.name "$GITHUB_ACTOR"
      env:
        EMAIL: ${{secrets.EMAIL}}
    - run: git commit -m "Set dev image tag to short sha"
    - run: git push

  update-prd-image:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    needs:
    - build
    steps:
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: 3.8.6
    - run: git clone https://${GITHUB_TOKEN}@github.com/bikashpoudel2011/fleet-infra.git .
      env:
        REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: kustomize edit set image bikashpoudel2011/cheapest-exchange-rt:${GITHUB_REF#refs/*/}
      working-directory: ./deploy/overlays/production
    - run: git add .
    - run: |
        git config user.email "$EMAIL"
        git config user.name "$GITHUB_ACTOR"
      env:
        EMAIL: ${{secrets.EMAIL}}
    - run: git commit -m "Set prd image tag to latest tag"
    - run: git push